{
    "name": "StarboundCommands",
    "class": "starboundcommands.StarboundCommands",
    "details": {
        "live_update": true,
        "languages": ['english'],
        "version": 1.0,
        "description": "None",
        "dependencies": [],
        "load_first": [],
        "author": "Underbalanced",
        "url": "http://www.starnub.org"
    },
    "configuration": false,
    "commands": {
        "has": true,
        "name": "starbound",
        "alias": "sb",
    },
    "runnables": {
        "has": false,
        "runnables": []
    },
    "additional_permissions": [],
}
