{
  "name": "CommandParser",
  "class": "commandparser.CommandParser",
    "details": {
    "languages": ['english'],
    "version": 1.0,
    "description": "None",
    "dependencies": [
       {ChatParser: [1.0, 1.1]}
       ],
    "author": "Underbalanced",
    "url": "http://www.starnub.org"
  },
  "configuration": true,
  "commands": {
    "has": true,
    "name": "CommandParser",
    "alias": "cp",
  },
  "runnables": {
    "has": false,
    "runnables": []
  },
  "additional_permissions": [],
}