{
  "name": "Essentials",
  "class": "essentials.Essentials",
  "details": {
    "live_update": true,
    "languages": ['English'],
    "version": 1.0,
    "description": "None",
    "dependencies": [],
    "load_first": [],
    "author": "Underbalanced",
    "url": "http://www.starnub.org"
  },
  "configuration": true,
  "commands": {
    "has": true,
    "name": "essentials",
    "alias": "es",
  },
  "runnables": {
    "has": false, 
    "runnables": []
  }, 
  "additional_permissions": [],
}