{
    "chat_handling": {
        "handler": {
            "from_server": 'starnub', # starnub or starbound can handle server chat, if you select starbound the message replacment is nullified
            "from_player": 'starnub' # starnub or starbound can handle player chat, if you select starbound the player chat handling is nullliedied and that covers most options in this configuration
        }
    },
    "command_overrides": {
        "w": true, # Have this plugin handle /w - this will provide enhanced whispering
        "nick": true # Have this plugin handle /nick - this will provide enhanced nick name changing protection
    },
    "colors": {
        "server": {
            name: 'white',
            chat: 'white'
        },
        "global": {
            "name": '#FFFF00',
            "chat": '#FFFF00'
        }
    },
    "spam_filter": {
        "word_filter": {
            "enabled": true,
            "replacement": '*' # '' for nothing, char or word which will replace the filtered word
        },
        "block": {
            "reapeat": {
                "messages": true,
                "characters": true
            },
            "capitalization": {
                "enabled": true,
                "percentage": 50.0
            },
            "color_chat": false
        },
    },
    "name_rules": { #Set to true to allow, can be overriden with special permission
        "enabled": true,
        "auto_name_change": true,
        "notify_on_nick_changes": true, # Notifies the server through broadcast chat that a Nick name has changed and to what
        "length_cap": 25,
        "color": true,
        "special_characters": false,
        "spaces": {
            "single": true,
            "multi_space": false
        },
        "use": {
            word_filter: true,
            illegal_nicks: true
        }
    },
    "message_replacement": {
        "pvp": {
            "enabled": true,
            "channel": local,  # Options: local or broadcast
            "name_color": true, # Show players name color
            "mode": {
                "enabled": {
                "color": '#DC143C',
                "message": '%s is now in PVP mode.',
                },
                "disabled": {
                "color": '#00FF00',
                "message": '%s has left PVP mode.',
                }
            }
        }
    },
    "chat": {
        "settings": {
            "remove": {
                "starnub_account_delete": true, # Will delete all chat settings linked to this Account
                "starnub_character_delete": true # Will delete all chat settings linked to this Character

            }
        }
    },
    "chat_rooms": {
        "settings": {
            "auto_purge": true,
            "age": 30 # Purge after the chat room has been unused for this many days
        }

    }
}
