{
  "owner": 'StarNub',
  "name": 'ChatManager',
  "version": 1.0,
  "class": 'org.starnub.chatmanager.ChatManager',
  "has_configuration": true,
  "dependancies": ['ChatParser'],
  "additional_permissions": ['starnub.motd.ignore'],
  "author": 'Underbalanced',
  "url": 'http://www.starnub.org',
  "description": 'This will broadcast a MOTD to anyone who logs onto the server, based on the configuration set. This will ignore anyone with the ignore permission.'
}
