{
  "name": "ChatManager",
  "class": "org.starnub.chatmanager.ChatManager",
    "details": {
    "languages": ['english'],
    "version": 1.0,
    "description": "None",
    "dependencies": [
        {
          ChatParser: [1.0, 1.1]
        }
    ],
    "load_first": ['CommandParser'],
    "author": "Underbalanced",
    "url": "http://www.starnub.org"
  },
  "configuration": true,
  "commands": {
    "has": true,
    "name": "chatman",
    "alias": "cm",

  },
  "runnables": {
    "has": false,
    "runnables": []
  },
  "additional_permissions": [''],
}

